AllCops:
  TargetRubyVersion:
    2.4.1
  Exclude:
    - Guardfile
    - Gemfile
    - Gemfile.lock
    - db/schema.rb
    - db/migrate/*
    - db/default/*
    - config/initializers/*
    - config/environments/*
    - config/spring.rb
    - bin/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config.ru
    - Rakefile
    - config/routes.rb
    - lib/data/*
    - spec/models/skill_spec.rb


Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - app/services/json_weapon.rb

Style/AsciiIdentifiers:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BlockLength:
  Exclude:
    - spec/factories/*
    - spec/models/*
    - spec/services/*

Style/CaseIndentation:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

StringLiterals:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/TrailingWhitespace:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/SpaceBeforeComment:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

"Style/SymbolArray":
  Enabled: false

EndOfLine:
  Enabled: false
