version: '2'

volumes:

  postgres-data:
    driver: local
  gems:
    driver: local

services:

  db:
    image: postgres:latest
    ports:
      - 5444:5432
    volumes:
      - postgres-data:/var/lib/postresql/data
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: password

  test:
    image: jarmc/star_wars_fg:development
    command: rspec spec/
    build:
        context: .
        dockerfile: dev.Dockerfile
    working_dir: /code
    volumes:
        - .:/code
        - gems:/usr/local/bundle
    tty: true
    stdin_open: true
    environment:
        DATABASE_URL: "postgres://postgres:password@db:5432/star_wars_ffg_test"
        RACK_ENV: "test"
        RAILS_ENV: "test"

    links:
        - db

  web:
    image: jarmc/star_wars_fg:development
    command: rails server -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /code
    volumes:
      - .:/code
      - gems:/usr/local/bundle
    tty: true
    stdin_open: true
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/star_wars_ffg_dev"

    links:
      - db